# Generated by Django 4.1.2 on 2022-11-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_auto_20221118_2213"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registereduser",
            name="avatar",
            field=models.ImageField(
                default="/media/avatars/default.png", upload_to="media/avatars/"
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="avatar",
            field=models.ImageField(
                default="/media/avatars/default.png", upload_to="media/avatars/"
            ),
        ),
    ]
